version: '3'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  main-service:
    build:
      context: ./main      
      dockerfile: Dockerfile
    container_name: main-service
    ports:
      - "3000:3000"
      - "9464:9464"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["./flight-api"]

  provider-service:
    build:
      context: ./provider
      dockerfile: Dockerfile
    container_name: provider-service
    env_file:
      - .env
    depends_on:
      - redis
    command: ["./flight-api-provider"]
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
